version: 1
formatters:
  standard:
    format: '*** %(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard
    filename: topicsanalyser.log
    maxBytes: 1000000
    backupCount: 3
loggers:
  topicsAnalyserLogger:
    level: WARNING
    handlers: [file]
    propagate: no
root:
  level: WARNING
  handlers: [file]